### ISSUE TITLE
Deb version not starting 0.2.2-alpha

### ISSUE THREAD

**Issue by heniv96** [guiqui/k8Studio#35]
1.) sudo apt update
2.) sudo apt upgrade
3.) sudo apt install ./K8Studio_0.2.2-alpha_amd64.deb / sudo dpkg -i ./K8Studio_0.2.2-alpha_amd64.deb
3.) sudo reboot
4.) Select menu/programming/k8studio
Not starting.

Help?

innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /opt/K8Studio/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js
- /opt/K8Studio/resources/app.asar/node_modules/node-pty/lib/index.js
- /opt/K8Studio/resources/app.asar/dist/main/main.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:1082:15)
    at n._resolveFilename (node:electron/js2c/browser_init:2:117760)
    at Module._load (node:internal/modules/cjs/loader:927:27)
    at f._load (node:electron/js2c/asar_bundle:2:13377)
    at Module.require (node:internal/modules/cjs/loader:1148:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/opt/K8Studio/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:34:15)
    at Module._compile (node:internal/modules/cjs/loader:1269:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1324:10)
    at Module.load (node:internal/modules/cjs/loader:1124:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/K8Studio/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js',
    '/opt/K8Studio/resources/app.asar/node_modules/node-pty/lib/index.js',
    '/opt/K8Studio/resources/app.asar/dist/main/main.js',
    undefined
  ]
}
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /opt/K8Studio/resources/app.asar.unpacked/node_modules/node-pty/build/Release/pty.node)
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1869)
    at Module._extensions..node (node:internal/modules/cjs/loader:1354:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2096)
    at Module.load (node:internal/modules/cjs/loader:1124:32)
    at Module._load (node:internal/modules/cjs/loader:965:12)
    at f._load (node:electron/js2c/asar_bundle:2:13377)
    at Module.require (node:internal/modules/cjs/loader:1148:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/opt/K8Studio/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:29:11)
    at Module._compile (node:internal/modules/cjs/loader:1269:14)
[12109:0118/090536.967458:ERROR:object_proxy.cc(590)] Failed to call method: org.freedesktop.portal.Settings.Read: object_path= /org/freedesktop/portal/desktop: org.freedesktop.portal.Error.NotFound: Requested setting not found
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[12142:0118/090537.015384:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)

**Comment by mo-othman** [comment]
Hi @heniv96 I have it working on ubuntu. I will test it again by installing it the same way you mentioned
If you don't mind can you share the OS version and arch?

**Comment by mfahlandt** [comment]
can confirm this issue 

Ubuntu 20.04 
uname -a: 
Linux mario-desktop 5.4.0-169-generic #187-Ubuntu SMP Thu Nov 23 14:52:28 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

Installation was 
just with sudo:
sudo dpkg -i K8Studio_0.2.2-alpha_amd64.deb

Called it with: 
k8studio 

`innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /opt/K8Studio/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js
- /opt/K8Studio/resources/app.asar/node_modules/node-pty/lib/index.js
- /opt/K8Studio/resources/app.asar/dist/main/main.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:1082:15)
    at n._resolveFilename (node:electron/js2c/browser_init:2:117760)
    at Module._load (node:internal/modules/cjs/loader:927:27)
    at f._load (node:electron/js2c/asar_bundle:2:13377)
    at Module.require (node:internal/modules/cjs/loader:1148:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/opt/K8Studio/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:34:15)
    at Module._compile (node:internal/modules/cjs/loader:1269:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1324:10)
    at Module.load (node:internal/modules/cjs/loader:1124:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/K8Studio/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js',
    '/opt/K8Studio/resources/app.asar/node_modules/node-pty/lib/index.js',
    '/opt/K8Studio/resources/app.asar/dist/main/main.js',
    undefined
  ]
}
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /opt/K8Studio/resources/app.asar.unpacked/node_modules/node-pty/build/Release/pty.node)
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1869)
    at Module._extensions..node (node:internal/modules/cjs/loader:1354:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2096)
    at Module.load (node:internal/modules/cjs/loader:1124:32)
    at Module._load (node:internal/modules/cjs/loader:965:12)
    at f._load (node:electron/js2c/asar_bundle:2:13377)
    at Module.require (node:internal/modules/cjs/loader:1148:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/opt/K8Studio/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:29:11)
    at Module._compile (node:internal/modules/cjs/loader:1269:14)
[149342:0118/105041.690605:ERROR:object_proxy.cc(590)] Failed to call method: org.freedesktop.portal.Settings.Read: object_path= /org/freedesktop/portal/desktop: org.freedesktop.portal.Error.NotFound: Angeforderte Einstellung nicht gefunden
`

**Comment by lionelbeard** [comment]
Hi,

FYI, same issue on Debian 11.

**Comment by mo-othman** [comment]
Hi @heniv96 @mfahlandt
can you try this 
https://stackoverflow.com/questions/71940179/error-lib-x86-64-linux-gnu-libc-so-6-version-glibc-2-34-not-found

I can see "Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /opt/K8Studio/resources/app.asar.unpacked/node_modules/node-pty/build/Release/pty.node)
"  in the logs you have provided

**Comment by mo-othman** [comment]
Hi @lionelbeard 

can you try this 
https://stackoverflow.com/questions/71940179/error-lib-x86-64-linux-gnu-libc-so-6-version-glibc-2-34-not-found


if you are having 
"Error: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /opt/K8Studio/resources/app.asar.unpacked/node_modules/node-pty/build/Release/pty.node)
"

**Comment by lionelbeard** [comment]
This is my professional laptop and I can play with libc6 update. There is no glibc2.34 update in official debian repo.
So for now this version of k8studio is not compatible with debian 11.
Thanks.

**Comment by mo-othman** [comment]
Hi @lionelbeard Thanks for the information! we will investigate into it

**Comment by mo-othman** [comment]
Hello @heniv96, @mfahlandt, @lionelbeard,

I wanted to inform you that we've just released 0.2.3 there's another version of the .deb file, specifically tailored to address the issues you've been experiencing. You can find this latest version on the releases page, and it should be named with the extension .old-deb.deb.

Moving forward, there will be only one .deb file in future updates.

Thank you for your patience and cooperation. If you encounter any further issues or have feedback, please don't hesitate to reach out.

**Comment by mfahlandt** [comment]
Hey @mo-othman 
thanks a lot for providing a fix. 

The new version is working like a charm! Thanks for this. 

I also did some digging. Ubuntu 20.04 only supports glibc up to 2.31 there i believe lies the problem. So it either needs to be compiled on an old machine oder using static link. 

Hope this input helps! 

But thanks again, will take a look at the software now

**Comment by mo-othman** [comment]
@mfahlandt Yeah exactly we are using node-pty 
so in the deb 11 version we have downgraded the node-pty, we've opted to keep it as a standalone in order to avoid any potential impacts on other builds.

Looking forward to hearing your feedbacks

**Comment by mo-othman** [comment]
Fixed in release 0.2.3-alpha

**Comment by lionelbeard** [comment]
I confirm, it is working now under Debian 11.
But now I don't understand why I have to create an account to use this tools, but this is another topic…
Thanks!
