### ISSUE TITLE
ResourceApiList.load error

### ISSUE THREAD

**Issue by bizio996** [guiqui/k8Studio#84]
Hi, I've just put my kube config cluster on k8 Studio, but now showing nothing, below the log k8Studio app 

2024-05-08 23:09:25.663] [info]  Loading Cluster kubernetes-admin@kubernetes
[2024-05-08 23:09:25.694] [info]  Starting loading ResourceApiList for kubernetes-admin@kubernetes
[2024-05-08 23:10:40.731] [error] ResourceApiList.load error:
[2024-05-08 23:10:40.732] [error] Error: tunneling socket could not be established, statusCode=504
    at ClientRequest.a (file:///C:/Users/desk-user/AppData/Local/Programs/K8Studio/resources/app.asar/dist/renderer/main.a0783490.js:2:8836687)
    at Object.onceWrapper (node:events:628:26)
    at ClientRequest.emit (node:events:513:28)
    at Socket.socketOnData (node:_http_client:582:11)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
[2024-05-08 23:10:40.763] [info]  Loaded ResourceApiList for kubernetes-admin@kubernetes
[2024-05-08 23:11:00.767] [error] loadEssentialResources error:
[2024-05-08 23:11:00.769] [error] Error: Timed out in 20000ms.
    at Fu.load (file:///C:/Users/desk-user/AppData/Local/Programs/K8Studio/resources/app.asar/dist/renderer/main.a0783490.js:2:6316752)
    at async file:///C:/Users/desk-user/AppData/Local/Programs/K8Studio/resources/app.asar/dist/renderer/main.a0783490.js:2:6487087
[2024-05-08 23:11:00.812] [error] Error Loading cluster Timed out in 20000ms.
[2024-05-08 23:11:00.814] [error] Error: Timed out in 20000ms.
    at Fu.load (file:///C:/Users/desk-user/AppData/Local/Programs/K8Studio/resources/app.asar/dist/renderer/main.a0783490.js:2:6316752)
    at async file:///C:/Users/desk-user/AppData/Local/Programs/K8Studio/resources/app.asar/dist/renderer/main.a0783490.js:2:6487087

---------
App Version 1.0.8-beta
Arch: x64
Platform: win32
osRelease: 10.0.19045
Locale: it
---------

**Comment by guiqui** [comment]
Sorry for the late response, one question are you using a proxy?
